language: rust
sudo: false
env:
  - FEATURES='serde-1'
matrix:
  include:
    - rust: stable
    - rust: stable
      env:
      - FEATURES='serde-1'
    - rust: 1.22.1
      env:
      - FEATURES='array-sizes-33-128 array-sizes-129-255'
    - rust: stable
      env:
      - FEATURES='array-sizes-33-128 array-sizes-129-255'
    - rust: beta
    - rust: nightly
      env:
      - ARRAYVECTEST_ENSURE_UNION=1
    - rust: nightly
      env:
      - FEATURES='serde'
      - ARRAYVECTEST_ENSURE_UNION=1
    - rust: nightly
      env:
      - FEATURES='serde-1'
      - ARRAYVECTEST_ENSURE_UNION=1
    - rust: nightly
      env:
      - FEATURES='array-sizes-33-128 array-sizes-129-255'
branches:
  only:
    - master
    - 0.4
script:
  - |
      cargo build -v --no-default-features &&
      cargo build -v --features "$FEATURES" &&
      cargo test -v --features "$FEATURES" &&
      cargo test -v --release --features "$FEATURES" &&
      cargo bench -v --features "$FEATURES" --no-run &&
      cargo doc -v --features "$FEATURES" &&
      cargo build -v --manifest-path=nodrop/Cargo.toml &&
      cargo test -v --manifest-path=nodrop/Cargo.toml
