[package]
name = "arrayvec"
version = "0.1.2"
authors = ["bluss"]
license = "MIT/Apache-2.0"

description = "A vector with a fixed capacity."
documentation = "http://bluss.github.io/arrayvec"
repository = "https://github.com/bluss/arrayvec"

keywords = ["stack", "vector", "array", "container", "data-structure"]

[dependencies]

nodrop = "0.1"
