[package]
name = "arrayvec"
version = "0.1.0"
authors = ["bluss"]

description = "A vector with a fixed capacity."
documentation = "http://bluss.github.io/arrayvec"
repository = "https://github.com/bluss/arrayvec"

keywords = ["stack", "vector", "array", "container", "data-structure"]
